services:
  gbvsr-gm-bot:
    stop_grace_period: 60s
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - TZ=Europe/Paris
    build: .
    env_file:
      - .env
    image: pollux_gm_bot:latest
    container_name: gbvsr-gm-bot
    restart: unless-stopped
    volumes:
      - ../gbvsr-gm-watch/jsons:/jsons
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"